### ISSUE TITLE
Add option to use an alternate maven settings file

### ISSUE THREAD

**Issue by oconnormi** [connexta/libero#15]
This should be an option from the command line as well as in the project config file

**Comment by lessarderic** [comment]
Should this be part of the config file or just be a command line option?

If we put this in the config file, it means that each project could have it's own settings file when _libera_ is run. However, I'm not sure that it would make sense to allow multiple files to be specified at the command line, which would make things inconsistent.

Is there anything that would require someone to have separate settings file or could everything be put in a single one?
