### ISSUE TITLE
Change or provide an option to customize commit messages

### ISSUE THREAD

**Issue by lessarderic** [connexta/libero#27]
Libero currently uses the commit messages `[libero] prepare release <release>` and `[libero] prepare for next development iteration`. Since `libero` isn't quite as well known as `maven-release-plugin`, we should consider removing it, making it a little more explicit (e.g. `[libero release tool]`) and/or provide a way to configure the commit messages that are used.

@brendan-hofmann, is this what you were looking for?

**Comment by brendan-hofmann** [comment]
Yup. 👍 

I don't think I quite made the connection that libero is actually the name of the release helper, that goes a long way towards explaining it. Still, indicating that `libero` is a release tool or helper of some kind in those messages would be good, imho.
